using Microsoft.EntityFrameworkCore;

namespace Qib.ServicePortal.Api.Infrastructure.Data;

public static class RuntimeSchema
{
    public static async Task EnsureAsync(ServicePortalDbContext db, ILogger logger, CancellationToken cancellationToken = default)
    {
        if (!db.Database.IsNpgsql())
        {
            return;
        }

        logger.LogInformation("ASP.NET backend startup: ensuring additive runtime schema");
        await EnsureUsersSchemaAsync(db, cancellationToken);
        await EnsureNotificationsSchemaAsync(db, cancellationToken);
        await EnsureMessagingSchemaAsync(db, cancellationToken);
        await EnsureDocumentSchemaAsync(db, cancellationToken);
        await EnsureOperationalSchemaAsync(db, cancellationToken);
    }

    private static async Task EnsureUsersSchemaAsync(ServicePortalDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE users ADD COLUMN IF NOT EXISTS "SpecializedSectionId" BIGINT NULL REFERENCES specialized_sections ("Id") ON DELETE SET NULL;
            ALTER TABLE users ADD COLUMN IF NOT EXISTS "RelationshipType" VARCHAR(80) NOT NULL DEFAULT 'employee';
            CREATE INDEX IF NOT EXISTS "IX_users_SpecializedSectionId" ON users ("SpecializedSectionId");
            """,
            cancellationToken);
    }

    private static async Task EnsureNotificationsSchemaAsync(ServicePortalDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS notifications (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "Title" VARCHAR(255) NOT NULL,
                "Body" TEXT NOT NULL,
                "Channel" VARCHAR(80) NOT NULL DEFAULT 'system',
                "RelatedRoute" VARCHAR(300) NULL,
                "IsRead" BOOLEAN NOT NULL DEFAULT FALSE,
                "ReadAt" TIMESTAMPTZ NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_notifications_UserId_IsRead_CreatedAt" ON notifications ("UserId", "IsRead", "CreatedAt");
            CREATE INDEX IF NOT EXISTS "IX_notifications_Channel" ON notifications ("Channel");
            ALTER TABLE notifications ADD COLUMN IF NOT EXISTS "RelatedRoute" VARCHAR(300) NULL;
            ALTER TABLE notifications ADD COLUMN IF NOT EXISTS "ReadAt" TIMESTAMPTZ NULL;
            """,
            cancellationToken);
    }

    private static async Task EnsureMessagingSchemaAsync(ServicePortalDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS message_types (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Code" VARCHAR(100) NOT NULL,
                "NameAr" VARCHAR(255) NOT NULL,
                "NameEn" TEXT NULL,
                "Color" VARCHAR(30) NOT NULL DEFAULT '#1d4ed8',
                "Icon" VARCHAR(80) NULL,
                "IsOfficial" BOOLEAN NOT NULL DEFAULT FALSE,
                "RequiresRequest" BOOLEAN NOT NULL DEFAULT FALSE,
                "RequiresAttachment" BOOLEAN NOT NULL DEFAULT FALSE,
                "ShowInPdf" BOOLEAN NOT NULL DEFAULT FALSE,
                "AllowReply" BOOLEAN NOT NULL DEFAULT TRUE,
                "VisibleToRequester" BOOLEAN NOT NULL DEFAULT TRUE,
                "SortOrder" INTEGER NOT NULL DEFAULT 100,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_message_types_Code" ON message_types ("Code");
            ALTER TABLE message_types ADD COLUMN IF NOT EXISTS "Description" TEXT NULL;

            CREATE TABLE IF NOT EXISTS message_classifications (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Code" VARCHAR(100) NOT NULL,
                "NameAr" VARCHAR(255) NOT NULL,
                "NameEn" TEXT NULL,
                "Color" VARCHAR(30) NOT NULL DEFAULT '#64748b',
                "IsConfidential" BOOLEAN NOT NULL DEFAULT FALSE,
                "RequiresPermission" BOOLEAN NOT NULL DEFAULT FALSE,
                "SortOrder" INTEGER NOT NULL DEFAULT 100,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_message_classifications_Code" ON message_classifications ("Code");
            ALTER TABLE message_classifications ADD COLUMN IF NOT EXISTS "Description" TEXT NULL;
            ALTER TABLE message_classifications ADD COLUMN IF NOT EXISTS "ShowInPdf" BOOLEAN NOT NULL DEFAULT FALSE;
            ALTER TABLE message_classifications ADD COLUMN IF NOT EXISTS "ShowInReports" BOOLEAN NOT NULL DEFAULT TRUE;
            ALTER TABLE message_classifications ADD COLUMN IF NOT EXISTS "AllowAttachmentDownload" BOOLEAN NOT NULL DEFAULT TRUE;
            ALTER TABLE message_classifications ADD COLUMN IF NOT EXISTS "LogDownloads" BOOLEAN NOT NULL DEFAULT FALSE;
            ALTER TABLE message_classifications ADD COLUMN IF NOT EXISTS "RequiresSpecialPermission" BOOLEAN NOT NULL DEFAULT FALSE;

            CREATE TABLE IF NOT EXISTS messages (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Subject" VARCHAR(300) NOT NULL,
                "Body" TEXT NOT NULL,
                "SenderId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE RESTRICT,
                "MessageTypeId" BIGINT NOT NULL REFERENCES message_types ("Id") ON DELETE RESTRICT,
                "ClassificationId" BIGINT NULL REFERENCES message_classifications ("Id") ON DELETE SET NULL,
                "ParentMessageId" BIGINT NULL REFERENCES messages ("Id") ON DELETE SET NULL,
                "RelatedRequestId" BIGINT NULL REFERENCES requests ("Id") ON DELETE SET NULL,
                "Priority" VARCHAR(30) NOT NULL DEFAULT 'normal',
                "IsOfficial" BOOLEAN NOT NULL DEFAULT FALSE,
                "IncludeInRequestPdf" BOOLEAN NOT NULL DEFAULT FALSE,
                "SentAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_messages_SentAt" ON messages ("SentAt");
            CREATE INDEX IF NOT EXISTS "IX_messages_RelatedRequestId" ON messages ("RelatedRequestId");
            CREATE INDEX IF NOT EXISTS "IX_messages_MessageTypeId" ON messages ("MessageTypeId");
            ALTER TABLE messages ADD COLUMN IF NOT EXISTS "OfficialReferenceNumber" VARCHAR(100) NULL;
            ALTER TABLE messages ADD COLUMN IF NOT EXISTS "OfficialPdfDocumentId" BIGINT NULL;
            ALTER TABLE messages ADD COLUMN IF NOT EXISTS "OfficialStatus" VARCHAR(40) NOT NULL DEFAULT 'sent';

            CREATE TABLE IF NOT EXISTS message_recipients (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MessageId" BIGINT NOT NULL REFERENCES messages ("Id") ON DELETE CASCADE,
                "RecipientId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "IsRead" BOOLEAN NOT NULL DEFAULT FALSE,
                "ReadAt" TIMESTAMPTZ NULL,
                "IsArchived" BOOLEAN NOT NULL DEFAULT FALSE,
                "ArchivedAt" TIMESTAMPTZ NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_message_recipients_MessageId_RecipientId" ON message_recipients ("MessageId", "RecipientId");
            CREATE INDEX IF NOT EXISTS "IX_message_recipients_RecipientId_IsRead_IsArchived" ON message_recipients ("RecipientId", "IsRead", "IsArchived");

            CREATE TABLE IF NOT EXISTS message_attachments (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MessageId" BIGINT NOT NULL REFERENCES messages ("Id") ON DELETE CASCADE,
                "FileName" VARCHAR(255) NOT NULL,
                "StoredFileName" VARCHAR(255) NOT NULL,
                "StoragePath" TEXT NOT NULL,
                "ContentType" VARCHAR(150) NOT NULL DEFAULT 'application/octet-stream',
                "FileSize" BIGINT NOT NULL,
                "Checksum" TEXT NOT NULL,
                "UploadedByUserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE RESTRICT,
                "UploadedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
            );
            CREATE INDEX IF NOT EXISTS "IX_message_attachments_MessageId" ON message_attachments ("MessageId");

            CREATE TABLE IF NOT EXISTS message_templates (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Code" VARCHAR(100) NOT NULL,
                "NameAr" VARCHAR(255) NOT NULL,
                "NameEn" TEXT NULL,
                "MessageTypeId" BIGINT NULL REFERENCES message_types ("Id") ON DELETE SET NULL,
                "SubjectTemplate" TEXT NOT NULL,
                "BodyTemplate" TEXT NOT NULL,
                "SortOrder" INTEGER NOT NULL DEFAULT 100,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_message_templates_Code" ON message_templates ("Code");

            CREATE TABLE IF NOT EXISTS official_letterhead_templates (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "NameAr" VARCHAR(255) NOT NULL,
                "NameEn" TEXT NULL,
                "Code" VARCHAR(100) NOT NULL,
                "LogoPath" TEXT NULL,
                "HeaderHtml" TEXT NOT NULL DEFAULT '',
                "FooterHtml" TEXT NOT NULL DEFAULT '',
                "PrimaryColor" VARCHAR(30) NOT NULL DEFAULT '#0f5132',
                "SecondaryColor" VARCHAR(30) NOT NULL DEFAULT '#9bd84e',
                "ShowPageNumber" BOOLEAN NOT NULL DEFAULT TRUE,
                "ShowConfidentialityLabel" BOOLEAN NOT NULL DEFAULT TRUE,
                "IsDefault" BOOLEAN NOT NULL DEFAULT FALSE,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_official_letterhead_templates_Code" ON official_letterhead_templates ("Code");

            CREATE TABLE IF NOT EXISTS official_message_settings (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "IsEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
                "DefaultLetterheadTemplateId" BIGINT NULL REFERENCES official_letterhead_templates ("Id") ON DELETE SET NULL,
                "OfficialMessageRequiresApproval" BOOLEAN NOT NULL DEFAULT FALSE,
                "IncludeOfficialMessagesInRequestPdf" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowPreviewForAllUsers" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowUnverifiedSignature" BOOLEAN NOT NULL DEFAULT FALSE,
                "AllowSignatureUploadByUser" BOOLEAN NOT NULL DEFAULT TRUE,
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE official_message_settings ADD COLUMN IF NOT EXISTS "AllowUnverifiedSignature" BOOLEAN NOT NULL DEFAULT FALSE;
            ALTER TABLE official_message_settings ADD COLUMN IF NOT EXISTS "AllowSignatureUploadByUser" BOOLEAN NOT NULL DEFAULT TRUE;

            CREATE TABLE IF NOT EXISTS official_message_documents (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MessageId" BIGINT NOT NULL REFERENCES messages ("Id") ON DELETE CASCADE,
                "RelatedRequestId" BIGINT NULL REFERENCES requests ("Id") ON DELETE SET NULL,
                "LetterheadTemplateId" BIGINT NOT NULL REFERENCES official_letterhead_templates ("Id") ON DELETE RESTRICT,
                "SignatureId" BIGINT NULL,
                "ReferenceNumber" TEXT NULL,
                "PdfFilePath" TEXT NOT NULL,
                "FileSize" BIGINT NOT NULL,
                "Checksum" TEXT NOT NULL,
                "GeneratedByUserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE RESTRICT,
                "GeneratedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE official_message_documents ADD COLUMN IF NOT EXISTS "SignatureId" BIGINT NULL;
            CREATE INDEX IF NOT EXISTS "IX_official_message_documents_MessageId" ON official_message_documents ("MessageId");
            """,
            cancellationToken);
    }

    private static async Task EnsureDocumentSchemaAsync(ServicePortalDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS document_categories (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "NameAr" VARCHAR(255) NOT NULL,
                "NameEn" TEXT NULL,
                "Code" VARCHAR(100) NOT NULL,
                "Description" TEXT NULL,
                "Icon" VARCHAR(80) NULL,
                "Color" VARCHAR(30) NOT NULL DEFAULT '#0f5132',
                "SortOrder" INTEGER NOT NULL DEFAULT 100,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_document_categories_Code" ON document_categories ("Code");

            CREATE TABLE IF NOT EXISTS documents (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CategoryId" BIGINT NOT NULL REFERENCES document_categories ("Id") ON DELETE RESTRICT,
                "TitleAr" VARCHAR(300) NOT NULL,
                "TitleEn" TEXT NULL,
                "DocumentNumber" VARCHAR(100) NULL,
                "Description" TEXT NULL,
                "OwnerDepartmentId" BIGINT NULL REFERENCES departments ("Id") ON DELETE SET NULL,
                "Classification" VARCHAR(40) NOT NULL DEFAULT 'internal',
                "Status" VARCHAR(40) NOT NULL DEFAULT 'active',
                "CurrentVersionId" BIGINT NULL,
                "RequiresAcknowledgement" BOOLEAN NOT NULL DEFAULT FALSE,
                "Keywords" TEXT NULL,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedByUserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE RESTRICT,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_documents_CategoryId" ON documents ("CategoryId");
            CREATE INDEX IF NOT EXISTS "IX_documents_DocumentNumber" ON documents ("DocumentNumber");
            CREATE INDEX IF NOT EXISTS "IX_documents_Classification" ON documents ("Classification");
            CREATE INDEX IF NOT EXISTS "IX_documents_Status" ON documents ("Status");

            CREATE TABLE IF NOT EXISTS document_versions (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DocumentId" BIGINT NOT NULL REFERENCES documents ("Id") ON DELETE CASCADE,
                "VersionNumber" VARCHAR(40) NOT NULL,
                "FileName" VARCHAR(255) NOT NULL,
                "StoredFileName" VARCHAR(255) NOT NULL,
                "FilePath" TEXT NOT NULL,
                "FileSize" BIGINT NOT NULL,
                "MimeType" VARCHAR(150) NOT NULL DEFAULT 'application/pdf',
                "Checksum" TEXT NOT NULL,
                "IssueDate" DATE NULL,
                "EffectiveDate" DATE NULL,
                "ReviewDate" DATE NULL,
                "UploadedByUserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE RESTRICT,
                "UploadedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "ChangeSummary" TEXT NULL,
                "IsCurrent" BOOLEAN NOT NULL DEFAULT FALSE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_document_versions_DocumentId_VersionNumber" ON document_versions ("DocumentId", "VersionNumber");
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_documents_document_versions_CurrentVersionId'
                ) THEN
                    ALTER TABLE documents
                    ADD CONSTRAINT "FK_documents_document_versions_CurrentVersionId"
                    FOREIGN KEY ("CurrentVersionId") REFERENCES document_versions ("Id") ON DELETE SET NULL;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS document_permissions (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CategoryId" BIGINT NULL REFERENCES document_categories ("Id") ON DELETE CASCADE,
                "DocumentId" BIGINT NULL REFERENCES documents ("Id") ON DELETE CASCADE,
                "RoleId" BIGINT NULL REFERENCES roles ("Id") ON DELETE CASCADE,
                "DepartmentId" BIGINT NULL REFERENCES departments ("Id") ON DELETE CASCADE,
                "CanView" BOOLEAN NOT NULL DEFAULT TRUE,
                "CanDownload" BOOLEAN NOT NULL DEFAULT FALSE,
                "CanPrint" BOOLEAN NOT NULL DEFAULT FALSE,
                "CanManage" BOOLEAN NOT NULL DEFAULT FALSE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_document_permissions_CategoryId" ON document_permissions ("CategoryId");
            CREATE INDEX IF NOT EXISTS "IX_document_permissions_DocumentId" ON document_permissions ("DocumentId");

            CREATE TABLE IF NOT EXISTS document_access_logs (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DocumentId" BIGINT NOT NULL REFERENCES documents ("Id") ON DELETE CASCADE,
                "VersionId" BIGINT NULL REFERENCES document_versions ("Id") ON DELETE SET NULL,
                "UserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE RESTRICT,
                "Action" VARCHAR(80) NOT NULL,
                "IpAddress" TEXT NULL,
                "UserAgent" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_document_access_logs_DocumentId_CreatedAt" ON document_access_logs ("DocumentId", "CreatedAt");
            CREATE INDEX IF NOT EXISTS "IX_document_access_logs_Action" ON document_access_logs ("Action");

            CREATE TABLE IF NOT EXISTS document_acknowledgements (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DocumentId" BIGINT NOT NULL REFERENCES documents ("Id") ON DELETE CASCADE,
                "VersionId" BIGINT NOT NULL REFERENCES document_versions ("Id") ON DELETE CASCADE,
                "UserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "AcknowledgedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_document_acknowledgements_DocumentId_VersionId_UserId"
                ON document_acknowledgements ("DocumentId", "VersionId", "UserId");
            """,
            cancellationToken);
    }

    private static async Task EnsureOperationalSchemaAsync(ServicePortalDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS user_sessions (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "SessionTokenHash" VARCHAR(255) NOT NULL,
                "RefreshTokenHash" TEXT NULL,
                "IpAddress" TEXT NULL,
                "UserAgent" TEXT NULL,
                "StartedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "LastSeenAt" TIMESTAMPTZ NULL,
                "ExpiresAt" TIMESTAMPTZ NULL,
                "RevokedAt" TIMESTAMPTZ NULL,
                "RevocationReason" TEXT NULL,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_sessions_SessionTokenHash" ON user_sessions ("SessionTokenHash");
            CREATE INDEX IF NOT EXISTS "IX_user_sessions_UserId_IsActive_LastSeenAt" ON user_sessions ("UserId", "IsActive", "LastSeenAt");

            CREATE TABLE IF NOT EXISTS user_login_attempts (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "LoginIdentifier" VARCHAR(255) NOT NULL,
                "IsSuccess" BOOLEAN NOT NULL DEFAULT FALSE,
                "FailureReason" VARCHAR(500) NULL,
                "IpAddress" TEXT NULL,
                "UserAgent" TEXT NULL,
                "AttemptedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_user_login_attempts_AttemptedAt" ON user_login_attempts ("AttemptedAt");
            CREATE INDEX IF NOT EXISTS "IX_user_login_attempts_LoginIdentifier_AttemptedAt" ON user_login_attempts ("LoginIdentifier", "AttemptedAt");

            CREATE TABLE IF NOT EXISTS system_health_checks (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CheckName" VARCHAR(120) NOT NULL,
                "Category" VARCHAR(80) NOT NULL DEFAULT 'general',
                "Status" VARCHAR(40) NOT NULL DEFAULT 'healthy',
                "LatencyMs" INTEGER NULL,
                "Message" TEXT NULL,
                "DetailsJson" TEXT NULL,
                "CheckedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_system_health_checks_Category_CheckedAt" ON system_health_checks ("Category", "CheckedAt");
            CREATE INDEX IF NOT EXISTS "IX_system_health_checks_Status" ON system_health_checks ("Status");

            CREATE TABLE IF NOT EXISTS system_health_alerts (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "AlertType" VARCHAR(100) NOT NULL,
                "Severity" VARCHAR(40) NOT NULL DEFAULT 'info',
                "Title" VARCHAR(255) NOT NULL,
                "Message" TEXT NULL,
                "RecommendedAction" TEXT NULL,
                "RelatedRoute" VARCHAR(300) NULL,
                "IsResolved" BOOLEAN NOT NULL DEFAULT FALSE,
                "ResolvedAt" TIMESTAMPTZ NULL,
                "ResolvedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_system_health_alerts_IsResolved_Severity_CreatedAt" ON system_health_alerts ("IsResolved", "Severity", "CreatedAt");

            CREATE TABLE IF NOT EXISTS system_health_metrics (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MetricName" VARCHAR(120) NOT NULL,
                "MetricValue" NUMERIC NOT NULL,
                "MetricUnit" VARCHAR(40) NULL,
                "Category" VARCHAR(80) NOT NULL DEFAULT 'general',
                "RecordedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_system_health_metrics_Category_RecordedAt" ON system_health_metrics ("Category", "RecordedAt");
            CREATE INDEX IF NOT EXISTS "IX_system_health_metrics_MetricName" ON system_health_metrics ("MetricName");

            CREATE TABLE IF NOT EXISTS system_health_settings (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DiskWarningPercent" INTEGER NOT NULL DEFAULT 80,
                "DiskCriticalPercent" INTEGER NOT NULL DEFAULT 90,
                "ErrorsWarningCount" INTEGER NOT NULL DEFAULT 10,
                "ErrorsCriticalCount" INTEGER NOT NULL DEFAULT 50,
                "DbLatencyWarningMs" INTEGER NOT NULL DEFAULT 300,
                "DbLatencyCriticalMs" INTEGER NOT NULL DEFAULT 1000,
                "AutoCheckEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
                "AutoCheckIntervalMinutes" INTEGER NOT NULL DEFAULT 15,
                "RetentionDays" INTEGER NOT NULL DEFAULT 30,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS database_backups (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BackupName" VARCHAR(255) NOT NULL,
                "BackupType" VARCHAR(60) NOT NULL DEFAULT 'manual',
                "Status" VARCHAR(60) NOT NULL DEFAULT 'pending',
                "FilePath" TEXT NULL,
                "FileSize" BIGINT NULL,
                "Checksum" TEXT NULL,
                "ErrorMessage" TEXT NULL,
                "CreatedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "StartedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "CompletedAt" TIMESTAMPTZ NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_database_backups_Status_StartedAt" ON database_backups ("Status", "StartedAt");

            CREATE TABLE IF NOT EXISTS database_jobs (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "JobType" VARCHAR(80) NOT NULL,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'pending',
                "ProgressPercent" INTEGER NOT NULL DEFAULT 0,
                "ResultJson" TEXT NULL,
                "ErrorMessage" TEXT NULL,
                "StartedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "StartedAt" TIMESTAMPTZ NULL,
                "FinishedAt" TIMESTAMPTZ NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_database_jobs_Status_CreatedAt" ON database_jobs ("Status", "CreatedAt");

            CREATE TABLE IF NOT EXISTS database_maintenance_logs (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Operation" VARCHAR(100) NOT NULL,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'success',
                "Message" TEXT NULL,
                "DetailsJson" TEXT NULL,
                "ActorUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_database_maintenance_logs_Operation_CreatedAt" ON database_maintenance_logs ("Operation", "CreatedAt");

            CREATE TABLE IF NOT EXISTS database_restore_jobs (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RestoreToken" VARCHAR(120) NOT NULL,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'pending',
                "SourceBackupPath" TEXT NULL,
                "PreviewJson" TEXT NULL,
                "ErrorMessage" TEXT NULL,
                "RequestedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CompletedAt" TIMESTAMPTZ NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_database_restore_jobs_RestoreToken" ON database_restore_jobs ("RestoreToken");

            CREATE TABLE IF NOT EXISTS rollback_points (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" VARCHAR(255) NOT NULL,
                "Version" VARCHAR(80) NULL,
                "BackupPath" TEXT NULL,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'available',
                "CreatedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_rollback_points_CreatedAt" ON rollback_points ("CreatedAt");

            CREATE TABLE IF NOT EXISTS system_versions (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Version" VARCHAR(80) NOT NULL,
                "BuildNumber" VARCHAR(100) NULL,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'active',
                "AppliedAt" TIMESTAMPTZ NULL,
                "AppliedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "Notes" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_system_versions_Version" ON system_versions ("Version");

            CREATE TABLE IF NOT EXISTS update_packages (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PackageName" VARCHAR(255) NOT NULL,
                "Version" VARCHAR(80) NOT NULL,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'uploaded',
                "FilePath" TEXT NULL,
                "FileSize" BIGINT NULL,
                "Checksum" TEXT NULL,
                "ManifestJson" TEXT NULL,
                "UploadedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_update_packages_Version_PackageName" ON update_packages ("Version", "PackageName");

            CREATE TABLE IF NOT EXISTS update_jobs (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PackageId" BIGINT NULL REFERENCES update_packages ("Id") ON DELETE SET NULL,
                "JobType" VARCHAR(80) NOT NULL DEFAULT 'update',
                "Status" VARCHAR(60) NOT NULL DEFAULT 'pending',
                "ProgressPercent" INTEGER NOT NULL DEFAULT 0,
                "CurrentStep" TEXT NULL,
                "ResultJson" TEXT NULL,
                "ErrorMessage" TEXT NULL,
                "StartedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "StartedAt" TIMESTAMPTZ NULL,
                "FinishedAt" TIMESTAMPTZ NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_update_jobs_Status_CreatedAt" ON update_jobs ("Status", "CreatedAt");

            CREATE TABLE IF NOT EXISTS update_logs (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UpdateJobId" BIGINT NULL REFERENCES update_jobs ("Id") ON DELETE CASCADE,
                "Level" VARCHAR(40) NOT NULL DEFAULT 'info',
                "Message" TEXT NOT NULL,
                "DetailsJson" TEXT NULL,
                "LoggedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_update_logs_UpdateJobId_LoggedAt" ON update_logs ("UpdateJobId", "LoggedAt");

            CREATE TABLE IF NOT EXISTS update_history (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Version" VARCHAR(80) NOT NULL,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'success',
                "StartedAt" TIMESTAMPTZ NULL,
                "CompletedAt" TIMESTAMPTZ NULL,
                "AppliedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "Summary" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_update_history_Version" ON update_history ("Version");

            CREATE TABLE IF NOT EXISTS saved_reports (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" VARCHAR(255) NOT NULL,
                "Description" TEXT NULL,
                "ReportType" VARCHAR(80) NOT NULL DEFAULT 'requests',
                "FiltersJson" TEXT NOT NULL DEFAULT '{{}}',
                "IsFavorite" BOOLEAN NOT NULL DEFAULT FALSE,
                "CreatedByUserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_saved_reports_CreatedByUserId_ReportType" ON saved_reports ("CreatedByUserId", "ReportType");

            CREATE TABLE IF NOT EXISTS report_templates (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "NameAr" VARCHAR(255) NOT NULL,
                "Code" VARCHAR(120) NOT NULL,
                "ReportType" VARCHAR(80) NOT NULL DEFAULT 'requests',
                "Description" TEXT NULL,
                "DefaultFiltersJson" TEXT NOT NULL DEFAULT '{{}}',
                "DefaultColumnsJson" TEXT NOT NULL DEFAULT '[]',
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_report_templates_Code" ON report_templates ("Code");

            CREATE TABLE IF NOT EXISTS scheduled_reports (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" VARCHAR(255) NOT NULL,
                "ReportTemplateId" BIGINT NULL REFERENCES report_templates ("Id") ON DELETE SET NULL,
                "Frequency" VARCHAR(40) NOT NULL DEFAULT 'monthly',
                "RunTime" TIME NOT NULL DEFAULT TIME '08:00',
                "RecipientsJson" TEXT NOT NULL DEFAULT '[]',
                "ExportFormat" VARCHAR(40) NOT NULL DEFAULT 'excel',
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "LastRunAt" TIMESTAMPTZ NULL,
                "NextRunAt" TIMESTAMPTZ NULL,
                "CreatedByUserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_scheduled_reports_IsActive_NextRunAt" ON scheduled_reports ("IsActive", "NextRunAt");

            CREATE TABLE IF NOT EXISTS report_export_logs (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ReportType" VARCHAR(80) NOT NULL,
                "ExportFormat" VARCHAR(40) NOT NULL DEFAULT 'excel',
                "FiltersJson" TEXT NOT NULL DEFAULT '{{}}',
                "FilePath" TEXT NULL,
                "ExportedByUserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "IpAddress" TEXT NULL,
                "ExportedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_report_export_logs_ReportType_ExportedAt" ON report_export_logs ("ReportType", "ExportedAt");

            CREATE TABLE IF NOT EXISTS ai_settings (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "IsEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
                "Provider" VARCHAR(80) NOT NULL DEFAULT 'ollama',
                "BaseUrl" TEXT NULL,
                "ModelName" VARCHAR(150) NULL,
                "MaxInputChars" INTEGER NOT NULL DEFAULT 5000,
                "SystemPrompt" TEXT NULL,
                "SettingsJson" TEXT NULL,
                "UpdatedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS ai_usage_logs (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "Feature" VARCHAR(100) NOT NULL,
                "InputChars" INTEGER NOT NULL DEFAULT 0,
                "OutputChars" INTEGER NOT NULL DEFAULT 0,
                "LatencyMs" INTEGER NOT NULL DEFAULT 0,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'success',
                "ErrorMessage" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_ai_usage_logs_Feature_CreatedAt" ON ai_usage_logs ("Feature", "CreatedAt");

            CREATE TABLE IF NOT EXISTS ai_prompt_templates (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Code" VARCHAR(120) NOT NULL,
                "NameAr" VARCHAR(255) NOT NULL,
                "PromptText" TEXT NOT NULL,
                "Feature" VARCHAR(100) NOT NULL,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ai_prompt_templates_Code" ON ai_prompt_templates ("Code");

            CREATE TABLE IF NOT EXISTS ai_health_checks (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Provider" VARCHAR(80) NOT NULL,
                "Status" VARCHAR(60) NOT NULL DEFAULT 'unknown',
                "LatencyMs" INTEGER NULL,
                "Message" TEXT NULL,
                "CheckedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_ai_health_checks_Provider_CheckedAt" ON ai_health_checks ("Provider", "CheckedAt");

            CREATE TABLE IF NOT EXISTS ai_feature_permissions (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Feature" VARCHAR(100) NOT NULL,
                "RoleId" BIGINT NULL REFERENCES roles ("Id") ON DELETE CASCADE,
                "UserId" BIGINT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "IsAllowed" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_ai_feature_permissions_Feature_RoleId_UserId" ON ai_feature_permissions ("Feature", "RoleId", "UserId");

            CREATE TABLE IF NOT EXISTS ai_feedback (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "Feature" VARCHAR(100) NOT NULL,
                "Rating" INTEGER NOT NULL DEFAULT 0,
                "Comments" TEXT NULL,
                "MetadataJson" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_ai_feedback_Feature_CreatedAt" ON ai_feedback ("Feature", "CreatedAt");

            CREATE TABLE IF NOT EXISTS messaging_settings (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "IsEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
                "MaxRecipients" INTEGER NOT NULL DEFAULT 1000,
                "AllowSendToUsers" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowSendToDepartments" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowMultipleRecipients" BOOLEAN NOT NULL DEFAULT TRUE,
                "RestrictToActiveUsers" BOOLEAN NOT NULL DEFAULT TRUE,
                "SettingsJson" TEXT NULL,
                "UpdatedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE messaging_settings ADD COLUMN IF NOT EXISTS "SettingsJson" TEXT NULL;

            CREATE TABLE IF NOT EXISTS message_attachment_settings (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "AllowAttachments" BOOLEAN NOT NULL DEFAULT TRUE,
                "MaxAttachments" INTEGER NOT NULL DEFAULT 5,
                "MaxFileSizeMb" INTEGER NOT NULL DEFAULT 10,
                "AllowedExtensionsJson" TEXT NOT NULL DEFAULT '["pdf","png","jpg","jpeg","doc","docx","xls","xlsx"]',
                "VirusScanEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
                "SettingsJson" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE message_attachment_settings ADD COLUMN IF NOT EXISTS "SettingsJson" TEXT NULL;

            CREATE TABLE IF NOT EXISTS message_notification_settings (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "NotifyOnNewMessage" BOOLEAN NOT NULL DEFAULT TRUE,
                "NotifyOnRead" BOOLEAN NOT NULL DEFAULT FALSE,
                "NotifyOnRequestLinkedMessage" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowUserPreference" BOOLEAN NOT NULL DEFAULT FALSE,
                "SettingsJson" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE message_notification_settings ADD COLUMN IF NOT EXISTS "SettingsJson" TEXT NULL;

            CREATE TABLE IF NOT EXISTS message_request_integration_settings (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "AllowLinkToRequest" BOOLEAN NOT NULL DEFAULT TRUE,
                "ShowMessagesTabInRequestDetails" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowSendMessageFromRequest" BOOLEAN NOT NULL DEFAULT TRUE,
                "IncludeOfficialMessagesInRequestPdf" BOOLEAN NOT NULL DEFAULT TRUE,
                "ExcludeInternalMessagesFromPdf" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowRequesterToViewMessages" BOOLEAN NOT NULL DEFAULT FALSE,
                "AllowApproversToViewRequestMessages" BOOLEAN NOT NULL DEFAULT TRUE,
                "SettingsJson" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE message_request_integration_settings ADD COLUMN IF NOT EXISTS "SettingsJson" TEXT NULL;

            CREATE TABLE IF NOT EXISTS message_retention_policies (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "AllowArchive" BOOLEAN NOT NULL DEFAULT TRUE,
                "MessageRetentionDays" INTEGER NOT NULL DEFAULT 2555,
                "AttachmentRetentionDays" INTEGER NOT NULL DEFAULT 2555,
                "PreventPermanentDelete" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowUserDeleteOwnMessage" BOOLEAN NOT NULL DEFAULT FALSE,
                "OfficialMessagesProtected" BOOLEAN NOT NULL DEFAULT TRUE,
                "ConfidentialMessagesProtected" BOOLEAN NOT NULL DEFAULT TRUE,
                "SettingsJson" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE message_retention_policies ADD COLUMN IF NOT EXISTS "SettingsJson" TEXT NULL;

            CREATE TABLE IF NOT EXISTS message_security_policies (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "HideSensitiveData" BOOLEAN NOT NULL DEFAULT TRUE,
                "MaskEmail" BOOLEAN NOT NULL DEFAULT TRUE,
                "MaskPhone" BOOLEAN NOT NULL DEFAULT TRUE,
                "MaskEmployeeNumber" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowContextSending" BOOLEAN NOT NULL DEFAULT TRUE,
                "AllowAttachmentsToModel" BOOLEAN NOT NULL DEFAULT FALSE,
                "SettingsJson" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE message_security_policies ADD COLUMN IF NOT EXISTS "SettingsJson" TEXT NULL;

            CREATE TABLE IF NOT EXISTS message_ai_settings (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "IsEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
                "ShowAssistantInCompose" BOOLEAN NOT NULL DEFAULT TRUE,
                "MaxInputChars" INTEGER NOT NULL DEFAULT 5000,
                "SystemPrompt" TEXT NULL,
                "SettingsJson" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE message_ai_settings ADD COLUMN IF NOT EXISTS "SettingsJson" TEXT NULL;

            CREATE TABLE IF NOT EXISTS message_auto_rules (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "EventCode" VARCHAR(120) NOT NULL,
                "IsEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
                "MessageTypeCode" VARCHAR(120) NULL,
                "MessageTypeId" BIGINT NULL REFERENCES message_types ("Id") ON DELETE SET NULL,
                "TemplateCode" VARCHAR(120) NULL,
                "SubjectTemplate" TEXT NOT NULL DEFAULT '',
                "BodyTemplate" TEXT NOT NULL DEFAULT '',
                "RecipientsJson" TEXT NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            ALTER TABLE message_auto_rules ADD COLUMN IF NOT EXISTS "MessageTypeId" BIGINT NULL REFERENCES message_types ("Id") ON DELETE SET NULL;
            ALTER TABLE message_auto_rules ADD COLUMN IF NOT EXISTS "SubjectTemplate" TEXT NOT NULL DEFAULT '';
            ALTER TABLE message_auto_rules ADD COLUMN IF NOT EXISTS "BodyTemplate" TEXT NOT NULL DEFAULT '';
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_message_auto_rules_EventCode" ON message_auto_rules ("EventCode");

            CREATE TABLE IF NOT EXISTS user_signatures (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" BIGINT NOT NULL REFERENCES users ("Id") ON DELETE CASCADE,
                "SignatureImagePath" TEXT NOT NULL,
                "SignatureLabel" TEXT NULL,
                "IsVerified" BOOLEAN NOT NULL DEFAULT FALSE,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "UploadedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "VerifiedByUserId" BIGINT NULL REFERENCES users ("Id") ON DELETE SET NULL,
                "VerifiedAt" TIMESTAMPTZ NULL,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS "IX_user_signatures_UserId_IsActive" ON user_signatures ("UserId", "IsActive");

            CREATE TABLE IF NOT EXISTS request_type_documents (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RequestTypeId" BIGINT NOT NULL REFERENCES request_types ("Id") ON DELETE CASCADE,
                "DocumentId" BIGINT NOT NULL REFERENCES documents ("Id") ON DELETE CASCADE,
                "IsRequiredReading" BOOLEAN NOT NULL DEFAULT FALSE,
                "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_request_type_documents_RequestTypeId_DocumentId" ON request_type_documents ("RequestTypeId", "DocumentId");
            """,
            cancellationToken);
    }
}
