from fastapi import APIRouter

from app.api.v1 import ai, ai_settings, audit, auth, dashboard, database_settings, documents, health, messages, messaging_settings, notifications, official_messages, realtime, reports, request_type_management, requests, settings, update_settings, updates, users

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(ai.router)
api_router.include_router(users.router)
api_router.include_router(users.roles_router)
api_router.include_router(users.permissions_router)
api_router.include_router(users.departments_router)
api_router.include_router(requests.router)
api_router.include_router(requests.approvals_router)
api_router.include_router(messages.router)
api_router.include_router(official_messages.letterheads_router)
api_router.include_router(official_messages.signatures_router)
api_router.include_router(official_messages.settings_signatures_router)
api_router.include_router(official_messages.official_messages_router)
api_router.include_router(official_messages.official_settings_router)
api_router.include_router(documents.router)
api_router.include_router(notifications.router)
api_router.include_router(realtime.router)
api_router.include_router(audit.router)
api_router.include_router(database_settings.router)
api_router.include_router(ai_settings.router)
api_router.include_router(messaging_settings.router)
api_router.include_router(update_settings.router)
api_router.include_router(settings.router)
api_router.include_router(updates.router)
api_router.include_router(settings.workflows_router)
api_router.include_router(settings.sla_rules_router)
api_router.include_router(request_type_management.router)
api_router.include_router(request_type_management.version_router)
api_router.include_router(request_type_management.request_management_router)
api_router.include_router(request_type_management.requests_router)
api_router.include_router(dashboard.router)
api_router.include_router(reports.router)
api_router.include_router(health.router)
